import crafttweaker.item.IItemStack;
# Staging Rails and Basic Transportation Infrastructure

var TransportationResearch as IItemStack[] = [

<minecraft:rail>,
<minecraft:detector_rail>,
<minecraft:golden_rail>,
<minecraft:activator_rail>,
<minecraft:tnt_minecart>,
<minecraft:hopper_minecart>,
<minecraft:chest_minecart>,
<minecraft:minecart>,
<minecraft:furnace_minecart>,
<forestry:cart.beehouse:1>,
<forestry:cart.beehouse>,
<railcraft:tool_crowbar_iron>,
<railcraft:signal>,
<railcraft:signal:1>,
<railcraft:signal:2>,
<railcraft:signal_dual>,
<railcraft:signal_dual:1>,
<railcraft:signal_dual:2>,
<railcraft:cart_spawner>,
<railcraft:detector>,
<railcraft:detector:1>,
<railcraft:detector:2>,
<railcraft:detector:3>,
<railcraft:detector:4>,
<railcraft:detector:5>,
<railcraft:detector:6>,
<railcraft:detector:7>,
<railcraft:detector:8>,
<railcraft:detector:9>,
<railcraft:detector:10>,
<railcraft:detector:11>,
<railcraft:detector:12>,
<railcraft:detector:13>,
<railcraft:bore>,
<railcraft:mow_track_layer>,
<railcraft:mow_track_relayer>,
<railcraft:mow_track_remover>,
<railcraft:mow_undercutter>,
<railcraft:cart_trade_station>,
<railcraft:cart_work>,
<railcraft:cart_jukebox>,
<railcraft:cart_bed>,
<railcraft:cart_redstone_flux>,
<railcraft:cart_pumpkin>,
<railcraft:cart_gift>,
<railcraft:track_kit:24>.withTag({railcraft: {kit: "railcraft_coupler"}}),
<railcraft:actuator>,
<railcraft:actuator:1>,
<railcraft:actuator:2>,
<railcraft:cart_tnt_wood>,
<railcraft:track_elevator>,
<railcraft:locomotive_creative>.withTag({model: "railcraft:default"}),
<railcraft:signal_box:2>,
<railcraft:signal_box:4>,
<railcraft:signal_box>,
<railcraft:signal_box:1>,
<railcraft:signal_box:3>,
<railcraft:signal_box:6>,
<railcraft:signal_box:5>,
<railcraft:track_kit:1>.withTag({railcraft: {kit: "railcraft_activator"}}),
<railcraft:track_kit:2>.withTag({railcraft: {kit: "railcraft_booster"}}),
<railcraft:track_kit:3>.withTag({railcraft: {kit: "railcraft_buffer"}}),
<railcraft:track_kit:4>.withTag({railcraft: {kit: "railcraft_control"}}),
<railcraft:track_kit:5>.withTag({railcraft: {kit: "railcraft_detector"}}),
<railcraft:track_kit:6>.withTag({railcraft: {kit: "railcraft_disembarking"}}),
<railcraft:track_kit:7>.withTag({railcraft: {kit: "railcraft_dumping"}}),
<railcraft:track_kit:8>.withTag({railcraft: {kit: "railcraft_embarking"}}),
<railcraft:track_kit:9>.withTag({railcraft: {kit: "railcraft_gated"}}),
<railcraft:track_kit:10>.withTag({railcraft: {kit: "railcraft_locking"}}),
<railcraft:track_kit:11>.withTag({railcraft: {kit: "railcraft_one_way"}}),
<railcraft:track_kit:15>.withTag({railcraft: {kit: "railcraft_messenger"}}),
<railcraft:track_kit:16>.withTag({railcraft: {kit: "railcraft_delayed"}}),
<railcraft:track_kit:17>.withTag({railcraft: {kit: "railcraft_priming"}}),
<railcraft:track_kit:18>.withTag({railcraft: {kit: "railcraft_launcher"}}),
<railcraft:track_kit:19>.withTag({railcraft: {kit: "railcraft_whistle"}}),
<railcraft:track_kit:20>.withTag({railcraft: {kit: "railcraft_locomotive"}}),
<railcraft:track_kit:21>.withTag({railcraft: {kit: "railcraft_throttle"}}),
<railcraft:track_kit:22>.withTag({railcraft: {kit: "railcraft_routing"}}),
<railcraft:track_kit:23>.withTag({railcraft: {kit: "railcraft_transition"}}),
<railcraft:manipulator:11>,
<railcraft:manipulator:8>,
<railcraft:manipulator:9>,
<railcraft:equipment:2>,
<railcraft:equipment:3>,
<railcraft:trade_station>,
<railcraft:force_track_emitter>,
<railcraft:track_flex_abandoned>,
<railcraft:track_flex_high_speed>,
<railcraft:track_flex_reinforced>,
<railcraft:track_flex_strap_iron>,
<railcraft:cart_cargo>,
<railcraft:cart_tank>,
<railcraft:cart_chest_void>,
<railcraft:tool_crowbar_steel>,
<railcraft:tool_magnifying_glass>,
<railcraft:armor_goggles>,
<railcraft:armor_overalls>,
<railcraft:rail>,
<railcraft:rail:1>,
<railcraft:rail:2>,
<railcraft:rail:3>,
<railcraft:rail:4>,
<railcraft:rail:5>,
<railcraft:tie>,
<railcraft:tie:1>,
<railcraft:rebar>,
<railcraft:manipulator>,
<railcraft:manipulator:1>,
<railcraft:manipulator:2>,
<railcraft:manipulator:3>,
<railcraft:manipulator:4>,
<railcraft:manipulator:5>,
<railcraft:manipulator:10>,
<railcraft:filter_blank>,
<railcraft:filter_type>,
<railcraft:filter_ore_dict>,
<railcraft:borehead_bronze>,
<railcraft:borehead_iron>,
<railcraft:borehead_steel>,
<railcraft:borehead_diamond>,
<railcraft:filter_bee>,
<railcraft:filter_bee_genome>,
<railcraft:tool_signal_surveyor>,
<railcraft:tool_signal_tuner>,
<railcraft:signal_lamp>,
<railcraft:tool_signal_label>,
<railcraft:circuit>,
<railcraft:circuit:1>,
<railcraft:circuit:2>,
<railcraft:circuit:3>,
<railcraft:tool_spike_maul_iron>,
<railcraft:tool_spike_maul_steel>,
<railcraft:railbed>,
<railcraft:railbed:1>,
<railcraft:logbook>,
<railcraft:tool_whistle_tuner>,
<railcraft:track_parts>,
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_detector"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_detector"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_detector"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_detector"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_activator"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_activator"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_activator"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_activator"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_activator"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_activator"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_activator"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_booster"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_booster"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_booster"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_booster"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_booster"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_booster"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_booster"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_buffer"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_buffer"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_buffer"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_buffer"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_buffer"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_control"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_control"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_control"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_control"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_control"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_detector"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_detector"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_detector"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_one_way"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_one_way"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_one_way"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_one_way"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_one_way"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_messenger"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_messenger"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_messenger"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_messenger"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_disembarking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_disembarking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_disembarking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_disembarking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_disembarking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_dumping"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_dumping"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_dumping"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_dumping"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_dumping"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_embarking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_embarking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_embarking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_embarking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_embarking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_gated"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_gated"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_gated"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_gated"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_gated"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_locking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_locking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_locking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_locking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_locking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_locking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_locking"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_whistle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_whistle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_locomotive"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_locomotive"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_locomotive"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_locomotive"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_locomotive"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_locomotive"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_locomotive"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_messenger"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_messenger"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_messenger"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_delayed"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_delayed"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_delayed"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_delayed"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_delayed"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_delayed"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_delayed"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_priming"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_priming"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_priming"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_priming"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_priming"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_priming"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_priming"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_launcher"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_launcher"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_launcher"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_launcher"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_launcher"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_whistle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_whistle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_whistle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_whistle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_whistle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_throttle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_throttle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_throttle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_throttle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_throttle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_throttle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_throttle"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_routing"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_routing"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_routing"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_routing"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_routing"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed", kit: "railcraft_transition"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_high_speed_electric", kit: "railcraft_transition"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_abandoned", kit: "railcraft_coupler"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_electric", kit: "railcraft_coupler"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_iron", kit: "railcraft_coupler"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_reinforced", kit: "railcraft_coupler"}}),
<railcraft:track_outfitted>.withTag({railcraft: {rail: "railcraft_strap_iron", kit: "railcraft_coupler"}}),
<railcraft:tool_notepad>,
<railcraft:locomotive_electric>.withTag({model: "railcraft:default"}),
<railcraft:track_flex_electric>,
<railcraft:track_flex_hs_electric>
];
for i in TransportationResearch {
mods.recipestages.Recipes.setRecipeStage("TransportationResearch", i);    
mods.ItemStages.addItemStage("TransportationResearch", i);
}